### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hyperupcall** [hyperupcall/bake#9]
### Roadmap for `v2.0.0`

- [x] Remove deprecated functionality
- [x] Move everything to single script (this project is already mostly decoupled from Basalt - do it fully)
- [x] Tests
- [x] Test to ensure `./bake` running through older bake scripts 100% works
- [ ] Determine minimum Bash version (4.2?). Print with fail if not met, and add test to min bash version to CI
- [ ] Remove `config` comment? but opt for creating global environment variable (most of these make sense to be globally set)
- [ ] Config variable for how printing is done (===== along whole width might be too much?)
- [ ] Close all other issues
